name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew build

      - name: Deploy to server
        if: github.ref == 'refs/heads/main'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER: root  # 서버의 사용자 이름
          SERVER_IP: 210.89.189.73  # 서버의 공인 IP 주소
          DEPLOY_PATH: /path/to/deploy  # 서버의 배포 경로
          PORT: 1024  # 서버의 SSH 포트 번호
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          scp -P $PORT -o StrictHostKeyChecking=no build/libs/*.jar $USER@$SERVER_IP:$DEPLOY_PATH
          ssh -p $PORT -o StrictHostKeyChecking=no $USER@$SERVER_IP << EOF
            pkill -f 'java -jar'
            nohup java -jar $DEPLOY_PATH/$(basename build/libs/*.jar) > $DEPLOY_PATH/nohup.out 2>&1 &
          EOF
